#!/usr/bin/env bash
# Use awk to extract IP and HTTP status code from Apache log file, and count occurrences
awk '{print $1, $9}' apache-access.log | sort | uniq -c | sort -nr | awk '{print $1, $2, $3}'
