#!/usr/bin/env bash
# Loop from 1 to 10 and display messages based on loop iteration

# Initialize counter
counter=1

# Loop until counter reaches 10
while [ $counter -le 10 ]; do
    # Check conditions for different messages based on loop iteration
    if [ $counter -eq 4 ]; then
        echo "bad luck"
    elif [ $counter -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    # Increment counter
    ((counter++))
done
