#!/usr/bin/env bash
# Displays numbers from 1 to 20 with specific messages for certain iterations

# Initialize counter
counter=1

# Loop until counter reaches 20
while [ $counter -le 20 ]; do
    # Display the current number
    echo $counter
    # Check conditions for different messages based on loop iteration using a case statement
    case $counter in
        4)
            echo "bad luck from China"
            ;;
        9)
            echo "bad luck from Japan"
            ;;
        17)
            echo "bad luck from Italy"
            ;;
    esac
    # Increment counter
    ((counter++))
done
