#!/usr/bin/env bash

# Install ufw firewall
apt-get install ufw -y

# Enable IPv6 in ufw
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw

# Disable ufw to apply changes
ufw disable 

# Enable ufw to apply changes
ufw enable

# Set default incoming policy to deny
ufw default deny incoming

# Allow outgoing traffic
ufw default allow outgoing

# Allow SSH (port 22)
ufw allow 22/tcp

# Allow HTTPS (port 443)
ufw allow 443/tcp

# Allow HTTP (port 80)
ufw allow 80/tcp
